### ISSUE TITLE
Feature: User can search for a movie

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#1]
## ⚙️ Feature

User can search for a movie

## 📐 Functionality

Can type the name of a movie and have results appear for the user to pick.

## 🖼️ Wireframes
<img width="782" alt="Screenshot 2022-04-18 153038" src="https://user-images.githubusercontent.com/99702540/163887687-172680d8-8eb3-4846-9491-0e2b26cfd7e6.png">
<img width="476" alt="Screenshot 2022-04-18 153059" src="https://user-images.githubusercontent.com/99702540/163887712-470795cd-91bb-47b4-9892-84fde28ed0f8.png">

## ✅ Task List

- [x] Make the search form and put it in data view = search form
- [x] Make sure styling matches markup
- [x] Make the search result page and put it in the data view = search results
- [x] make sure styling matches markup
- [x] add an event listener to the search button that sends an xml request for the user input
- [x] put the search results and pictures in a object
- [x] make a function that create a dom tree for search results
- [x] create a tree for each entry in the object
- [x] append these elements to the search results page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
