### ISSUE TITLE
Feature: User can view a search result's info

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#2]
## ⚙️ Feature

User can search result info

## 📐 Functionality

Once a search result is picked you can view its information in a new page

## 🖼️ Wireframes
<img width="467" alt="Screenshot 2022-04-18 155640" src="https://user-images.githubusercontent.com/99702540/163890111-64f98b89-ada4-427e-a8df-35d8836a9e62.png">

## ✅ Task List
- [x] Create a data-view for the card to display a movies info.
- [x] Create a card for showing the movie info of a search result.
- [x] Make sure it matches the wireframe.
- [x] Create a function that sends an xml request depending on the title clicked.
- [x] Make sure page changes views and all info filled in is correct.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
