### ISSUE TITLE
Feature: User can create a review

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#3]
## ⚙️ Feature

User can create a review
## 📐 Functionality

On the search info page you can click review and go to the review form to input a rating and experience 
## 🖼️ Wireframes
<img width="461" alt="Screenshot 2022-04-18 155924" src="https://user-images.githubusercontent.com/99702540/163890350-b220def2-4aed-4b2b-86f0-789b241eaa69.png">

<img width="595" alt="revFigma" src="https://user-images.githubusercontent.com/99702540/164555801-d638c241-b508-4b0f-835f-23aab52c699e.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a review button on the info page
- [x] Make a click event on the button to take you to the review form page
- [x] Create the review form page to take the user review and rating
- [x] Make sure it matches markup styling
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
