### ISSUE TITLE
Feature: User can view list of reviewed movies

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#4]
## ⚙️ Feature

User can view list of reviewed movies
## 📐 Functionality

When clicking save, the review and movie info show up at the top of the reviews page
## 🖼️ Wireframes

<img width="242" alt="Screenshot 2022-04-18 160207" src="https://user-images.githubusercontent.com/99702540/163890595-73cf59a7-23c1-43c0-915c-0d523f97f3da.png">

<img width="447" alt="Screenshot 2022-04-18 160153" src="https://user-images.githubusercontent.com/99702540/163890598-d0f53bc9-67d0-44ae-b221-9b1c771a693b.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make an event listener that saves the review data to the info data object.
- [x] Push the object to reviews in the data object.
- [x] Append the entries in data.reviews to the reviews page
- [x] Make sure the view switches when saving
- [x] Make sure styling matches the markup
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
