### ISSUE TITLE
Feature: User can edit reviews

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#5]
## ⚙️ Feature

User can edit reviews

## 📐 Functionality

While on the reviews page you can click the edit icon to go to the edit page with the info filled in, you can press save to update the data

## 🖼️ Wireframes
<img width="463" alt="Screenshot 2022-04-18 162134" src="https://user-images.githubusercontent.com/99702540/163892106-2fadfefe-e26b-4211-b5e1-92ae4c2c2f39.png">

<img width="242" alt="Screenshot 2022-04-18 162121" src="https://user-images.githubusercontent.com/99702540/163892111-cc9ffd98-6b7d-472c-9fea-e1971d0c79cd.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create Icons on each list element in review
- [x] Add an event listener for the icons to take the user to the review form page and moves the correct object to the editing property in data
- [x] Create a function that fills the input boxes with the already existing data
- [x] Add functionality to the submit review function that checks for data.editing and updates existing reviews
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
