### ISSUE TITLE
Feature: User can delete reviews

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#6]
## ⚙️ Feature

User can delete reviews

## 📐 Functionality

while on the edit page you can press delete, where a modal comes up asking if you are sure you want to delete, press cancel and return to the edit page or press delete to remove the review from the list

## 🖼️ Wireframes

<img width="463" alt="Screenshot 2022-04-18 162134" src="https://user-images.githubusercontent.com/99702540/163892341-d521e812-bf61-471e-9800-d4607169eb57.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make a hidden delete button in the html on the user review form
- [ ] When clicking the icon, unhide the delete button
- [ ] When clicking the delete button pull up a model asking for confirmation
- [ ] If the user clicks cancel bring the view back to the review form
- [ ] If the user clicks delete remove the entry associated with the editing ID from the reviews array and remove the li associated with the edit review from the ul.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
