### ISSUE TITLE
Feature: User can scroll images on reviews

### ISSUE THREAD

**Issue by kyleParrent** [kyleParrent/movie-registry#7]
## ⚙️ Feature

User can scroll images on reviews

## 📐 Functionality

while on the reviews page you can click the arrow next to the movie image to move through different images

## 🖼️ Wireframes

<img width="256" alt="Screenshot 2022-04-18 162747" src="https://user-images.githubusercontent.com/99702540/163892587-8e189cff-5ddd-4912-9775-b223baf62c7a.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
